# Colorscheme based on (https://github.com/rebelot/kanagawa.nvim/blob/master/extras/wezterm/kanagawa-dragon.lua)
[colors]
ansi = [
  "#0D0C0C",
  "#C4746E",
  "#8A9A7B",
  "#C4B28A",
  "#8BA4B0",
  "#A292A3",
  "#8EA4A2",
  "#C8C093"
]
brights = [
  "#A6A69C",
  "#E46876",
  "#87A987",
  "#E6C384",
  "#7FB4CA",
  "#938AA9",
  "#7AA89F",
  "#C5C9C5"
]
background = "#181616"
foreground = "#c5c9c5"
cursor_bg = "#C8C093"
cursor_border = "#C8C093"
cursor_fg = "#C8C093"
selection_bg = "#2D4F67"
selection_fg = "#C8C093"
scrollbar_thumb = "#16161D"
split = "#16161D"

[colors.tab_bar]
background = "#181616"

[colors.tab_bar.active_tab]
bg_color = "#181616"
fg_color = "#A292A3"

[colors.tab_bar.inactive_tab]
bg_color = "#181616"
fg_color = "#878787"

[colors.indexed]

[metadata]
aliases = []
name = "Kanagawa Dragon"
